//
//  FlightListInteractor.swift
//  Skyflow
//
//  Created by Luis Zapata on 14-10-19.
//  Copyright (c) 2019 Luis Zapata. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FlightListBusinessLogic
{
  func doSomething(request: FlightList.Something.Request)
}

protocol FlightListDataStore
{
  //var name: String { get set }
}

class FlightListInteractor: FlightListBusinessLogic, FlightListDataStore
{
  var presenter: FlightListPresentationLogic?
  var worker: FlightListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: FlightList.Something.Request)
  {
    print("interactor")
    worker = FlightListWorker()
    worker?.doSomeWork()
    
    let response = FlightList.Something.Response(res: request.req)
    presenter?.presentSomething(response: response)
  }
}
