//
//  FlightListPresenter.swift
//  Skyflow
//
//  Created by Luis Zapata on 14-10-19.
//  Copyright (c) 2019 Luis Zapata. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FlightListPresentationLogic
{
    func presentSomething(response: FlightList.Something.Response)
}

class FlightListPresenter: FlightListPresentationLogic
{
    var viewController: FlightListDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: FlightList.Something.Response)
    {
        print("presenter")
        let viewModel = FlightList.Something.ViewModel(data: response.res)
        viewController?.displaySomething(viewModel: viewModel)
    }
}
