//
//  FlightListModels.swift
//  Skyflow
//
//  Created by Luis Zapata on 14-10-19.
//  Copyright (c) 2019 Luis Zapata. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum FlightList
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
        var req: [Flight]
    }
    struct Response
    {
        var res: [Flight]
    }
    struct ViewModel
    {
        var data: [Flight]
    }
  }
}
